### ISSUE TITLE
Support for IOT-GATE-IMX8PLUS and SBC-IOT-IMX8PLUS?

### ISSUE THREAD

**Issue by Maher4Ever** [balena-os/balena-compulab#262]
Hi,

I'm interested in Plus variant of the Compulab i.MX8M IoT gateway and SBC lines because of their integrated NPU. Are there plans to add support for baleaOS to these variants? Also, do you expect this to take a lot of effort?

Thanks in advance!

**Comment by floion** [comment]
Hi @Maher4Ever we have added support for the IOT Gate imx8m plus. The device type is available in the balena dashboard and the code for it is here https://github.com/balena-os/balena-iot-gate-imx8plus

**Comment by Maher4Ever** [comment]
@floion Great, thanks! I'll make sure to check it out.
