### ISSUE TITLE
EtcherPro flashing instructions are wrong

### ISSUE THREAD

**Issue by konmouz** [balena-os/balena-compulab#33]
- To flash an image, the switch should be at position `ON`
- After removing the sd card and before booting, the switch should be at position `OFF`

<img width="1409" alt="Screenshot 2020-03-06 at 19 06 32" src="https://user-images.githubusercontent.com/15323961/76114435-f91c1600-5fdd-11ea-854a-93411270c0ee.png">

cc @vicgal

**Comment by vicgal** [comment]
Fixed in https://github.com/balena-os/balena-compulab/pull/36
